# Generated by Django 4.1.7 on 2023-03-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjulia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_elegida', models.CharField(max_length=35)),
                ('clase', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Usuario',
        ),
    ]
