# Generated by Django 4.1.7 on 2023-03-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appjulia', '0002_actividad_reserva_rename_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='DNI',
        ),
    ]
