# Generated by Django 4.1.7 on 2023-03-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appjulia', '0003_remove_usuario_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='clase',
        ),
    ]
