# Generated by Django 4.1.7 on 2023-03-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appjulia', '0004_remove_actividad_clase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='actividad_elegida',
            new_name='actividad',
        ),
    ]
